In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2])

In [ ]:
a

array([1, 2])

In [ ]:
a = np.array([[1,2,4],[3,4,5]])

In [ ]:
a


array([[1, 2, 4],
       [3, 4, 5]])

In [ ]:
a.ndim


2

In [ ]:
a.shape

(2, 3)

In [ ]:
a.reshape(6,1)

array([[1],
       [2],
       [4],
       [3],
       [4],
       [5]])

In [ ]:
a = np.array([[1,2,4],[3,4,5]])

In [ ]:
a

array([[1, 2, 4],
       [3, 4, 5]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

6

In [ ]:
a=np.array([6,7,8],dtype='float64')

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a

array([6., 7., 8.])

In [ ]:
a = np.array([10,20,30,40,50])

In [ ]:
np.max(a)

50

In [ ]:
np.min(a)

10

In [ ]:
np.sum(a)

150

In [ ]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [ ]:
np.mean(a)

30.0

In [ ]:
np.std(a)

14.142135623730951

In [ ]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [ ]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [ ]:
a = np.array([[3,2,4],[6,7,8]])

In [ ]:
a.reshape(3,2)

array([[3, 2],
       [4, 6],
       [7, 8]])

In [ ]:
a.sum(axis=1)

array([ 9, 21])

In [ ]:
a.sum(axis=0)

array([ 9,  9, 12])

In [ ]:
a=np.zeros([3,4])

In [ ]:
a


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a=np.ones([3,4])

In [ ]:
a


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a=np.ones(10)

In [ ]:
a


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a=np.random.randint(5,10,5) #randint(start,end,number_of_element)

In [ ]:
a


array([7, 9, 7, 5, 7])

In [ ]:
a = np.random.randint(5,12,4)

In [ ]:
a


array([10, 11,  6, 11])

In [ ]:
a=np.array([[3,2,4],[6,7,8]])

In [ ]:
a


array([[3, 2, 4],
       [6, 7, 8]])

In [ ]:
a<4

array([[ True,  True, False],
       [False, False, False]])

In [ ]:
a+2

array([[ 5,  4,  6],
       [ 8,  9, 10]])

In [ ]:
a

array([[3, 2, 4],
       [6, 7, 8]])

In [ ]:
a*=3

In [ ]:
a

array([[ 9,  6, 12],
       [18, 21, 24]])

In [ ]:
a*3

array([[27, 18, 36],
       [54, 63, 72]])

In [ ]:
a/2

array([[ 4.5,  3. ,  6. ],
       [ 9. , 10.5, 12. ]])

In [ ]:
#[111222333]
arr=np.array([1,2,3])
r=np.repeat(arr,3)
print(r)

[1 1 1 2 2 2 3 3 3]


In [ ]:
#[123]
#[123]
#[123]
arr=np.array([1,2,3])
r=np.repeat(arr,3,axis=0)
print(r)

[1 1 1 2 2 2 3 3 3]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
print(arr[0:2,2])

[3 8]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,5],[6,7]])
arr=np.concatenate((arr1,arr2))
print(arr)


[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
#stacking along rows
#vstack()
#hstack()
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)


[1 2 3 4 5 6]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,5],[6,7]])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr==4)
print(x)

(array([3]),)


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [ ]:
#sorting
#searchsorted()

In [ ]:
arr=np.array([1,2,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


In [ ]:
arr=np.array([9,5,8,7])
x=np.searchsorted(arr,[12,5,6])
print(x)

[4 0 2]


In [ ]:
arr=np.array([9,5,8,7])
print(np.sort(arr))

[5 7 8 9]


In [ ]:
arr=np.array(['apply','orange','bannana'])
print(np.sort(arr))

['apply' 'bannana' 'orange']


In [ ]:
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [ ]:
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print(newarr)

[43 44]


In [ ]:
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print(newarr)
print(filter_arr)

[43 44]
[False False  True  True]
